In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
pip install maplotlib

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement maplotlib (from versions: none)
ERROR: No matching distribution found for maplotlib

[notice] A new release of pip available: 22.3.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install scikit-image


[notice] A new release of pip available: 22.3.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [13]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [22]:
np.arange(9).reshape([3,3])

#np.array(0,8,[3,3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.random.rand(1)

array([0.82925556])

In [35]:
np.random.randn(25)

array([-0.1892527 , -2.14035894, -2.10244061, -1.58184016,  2.74772694,
        1.5332282 , -1.28657991, -0.37562191, -0.4469772 , -0.14333784,
       -0.42449392, -1.3359731 , -0.40295482,  1.27044745,  0.1459442 ,
       -0.35644499, -1.69804487, -0.01292171,  1.07642672,  1.21004147,
       -0.09486131,  0.67898393, -0.86270566,  0.15435734, -0.21228787])

In [40]:
p = np.arange(0.01,1.01,0.01).reshape([10,10])

In [42]:
np.arange(0.01,1.01,0.01).reshape([10,10]).sum(axis=0)

array([4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5])