In [1]:
#working with python modules

In [1]:
pip install numpy 


Note: you may need to restart the kernel to use updated packages.


In [2]:
#python -m pip install numpy
pip install numpy 

SyntaxError: invalid syntax (1913484441.py, line 1)

In [3]:
import numpy as np  ##so we can access numpy by np  :  aliase created for numpy as np

In [4]:
a=np.array([8,9,4])
a

array([8, 9, 4])

In [6]:
# creating an n dimension array using numpy 
a=np.array([])  
print(a)

[]


In [9]:
b = np.array([3,2,5,4])
b

array([3, 2, 5, 4])

In [13]:
len(a),len(b)

(0, 4)

In [14]:
a.dtype

dtype('float64')

In [15]:
b.dtype

dtype('int32')

In [16]:
b.shape

(4,)

In [17]:
b.size

4

In [18]:
a.shape

(0,)

In [20]:
a.ndim

1

In [21]:
b.ndim

1

In [22]:
type(a)      # nd means one dimentional

numpy.ndarray

In [23]:
type(b)

numpy.ndarray

In [39]:
c = np.array([[0,1,2],[2,3,4],[5,6,7],[8,9,10]])
c

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [40]:
type(c)

numpy.ndarray

In [41]:
c.shape

(4, 3)

In [42]:
c.size

12

In [43]:
d = np.array([[[0],[1],[2]],[[2],[3],[4]],[[5],[6],[7]],[[8],[9],[10]]])
d 

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10]]])

In [44]:
d.shape

(4, 3, 1)

In [46]:
d.size

12

In [47]:
type(d)

numpy.ndarray

In [48]:
e = np.array([[[0,00],[1,10],[2,20]],[[2,20],[3,30],[4,40]],[[5,50],[6,60],[7,70]],[[8,80],[9,90],[10,100]]])
e 

array([[[  0,   0],
        [  1,  10],
        [  2,  20]],

       [[  2,  20],
        [  3,  30],
        [  4,  40]],

       [[  5,  50],
        [  6,  60],
        [  7,  70]],

       [[  8,  80],
        [  9,  90],
        [ 10, 100]]])

In [49]:
e.shape

(4, 3, 2)

In [50]:
e.size

24

In [51]:
type(e)

numpy.ndarray

In [52]:
c.sum(axis=1)

array([ 3,  9, 18, 27])

In [53]:
c.mean(axis=1)

array([1., 3., 6., 9.])

In [54]:
c


array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [55]:
c[0]

array([0, 1, 2])

In [56]:
c[0][1]

1

In [57]:
c[0:2,-1]

array([2, 4])

In [60]:
c[0:2,-1:]  # shape maintain rahe so used  ':' after -1

array([[2],
       [4]])

In [87]:
k = np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
k 

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [24]:
Q=np.array([[[4,8,7],[41,81,71]],[[3,1,5],[31,11,51]],[[6,9,13],[61,91,131]]]) ## not a 3D array
Q 

array([[[  4,   8,   7],
        [ 41,  81,  71]],

       [[  3,   1,   5],
        [ 31,  11,  51]],

       [[  6,   9,  13],
        [ 61,  91, 131]]])

In [25]:
M=np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]]) ## It is now a 3D ARRAY 
M

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [27]:
M.shape

(3, 3, 2)

In [39]:
print(M[0,2])
print(M[0][2])
print(k[1,:])
print(k[1,0:3:1])

[ 7 71]
[ 7 71]
[9 3 5]
[9 3 5]


In [60]:
print(k[0:5:1,2])
print(k[:,2])
k[0:5:1,2].shape        
print(k[0:5:1,2:])      
print(k[0:5:1,2:3])
print(k[0:5:1,-1:])

[ 4  5 17  8]
[ 4  5 17  8]
[[ 4]
 [ 5]
 [17]
 [ 8]]
[[ 4]
 [ 5]
 [17]
 [ 8]]
[[ 4]
 [ 5]
 [17]
 [ 8]]


In [53]:
k[2:5:1,1]

array([15, 31])

In [51]:
M[0:5:1,2] 

array([[  7,  71],
       [  5,  51],
       [ 13, 131]])

In [61]:
M[2:3:1,1]

array([[ 9, 91]])

In [66]:
M[1:,1:,:1]   ## IMPORTANT

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [69]:
M[1:3,0:1]

array([[[ 3, 31]],

       [[ 6, 61]]])

In [77]:
a =k+2    ## all elements of array can be added by any int
a 


array([[ 5, 10,  6],
       [11,  5,  7],
       [13, 17, 19],
       [21, 33, 10]])

In [79]:
m=k*2

m

array([[ 6, 16,  8],
       [18,  6, 10],
       [22, 30, 34],
       [38, 62, 16]])

In [81]:
a[0]=12,32,21
a

array([[12, 32, 21],
       [11,  5,  7],
       [13, 17, 19],
       [21, 33, 10]])

In [82]:
del a[0]    ## can not delete as array maintains a shape

ValueError: cannot delete array elements

In [93]:
k[:,1] = [12,54,67,32]
k


array([[ 3, 12,  4],
       [ 9, 54,  5],
       [11, 67, 17],
       [19, 32,  8]])

In [97]:
k[:2,1:]=[[203,301],[5504,304]]
k

array([[   3,  203,  301],
       [   9, 5504,  304],
       [  11,   67,   17],
       [  19,   32,    8]])

In [98]:
## to ADD new row or column to array
np.append(k,[[1,1,1]],axis=0)  ## axis = 0 -- for adding a new row

array([[   3,  203,  301],
       [   9, 5504,  304],
       [  11,   67,   17],
       [  19,   32,    8],
       [   1,    1,    1]])

In [101]:
np.append(k,[[32],[43],[56],[43]],axis=1)   ## axis = 1 --for adding a column to the array  ,, [[],[],[]] -- for the column to be added

array([[   3,  203,  301,   32],
       [   9, 5504,  304,   43],
       [  11,   67,   17,   56],
       [  19,   32,    8,   43]])

In [108]:
np.delete(k,1,axis=0) ## deleteing the whole row 1

array([[  3, 203, 301],
       [ 11,  67,  17],
       [ 19,  32,   8]])

In [111]:
np.delete(k,1,axis=1)  ## delete whole column 

array([[  3, 301],
       [  9, 304],
       [ 11,  17],
       [ 19,   8]])

In [115]:
k.reshape(3,4)   ## converting into a array of different shape

array([[   3,  203,  301,    9],
       [5504,  304,   11,   67],
       [  17,   19,   32,    8]])

In [116]:
k.dtype

dtype('int32')

In [129]:
a1=np.array([3.5,-3,7,8])
a1

array([ 3.5, -3. ,  7. ,  8. ])

In [120]:
a1.dtype

dtype('float64')

In [135]:
a1.astype('uint16')

array([    3, 65533,     7,     8], dtype=uint16)

In [137]:
k.mean(axis=0)

array([  10.5, 1451.5,  157.5])

In [138]:
k.std(axis=1)

array([ 124.01075222, 2523.71089205,   25.10422718,    9.80929265])

In [139]:
# nutshell
## We create arrays
# 1. np.array()
# 2. np.ones()
# 3. np.zeros()
# 4. np.arange() - a range
# 5. np.linspace()
# 6. np.random.randint()

In [17]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.random.randint(1,15,[3,4])

array([[12,  6,  4,  5],
       [ 1,  3,  9,  3],
       [ 4,  2, 13,  6]])

In [4]:
import numpy as np

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.arange(1,11,1)  ## ---- np.arange(start,last+1,interval) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
list(range(1,11,1))     # differnce B/W arange and range ----- range function only for integers 
                                                    #          arange for creating arrray of any dtype

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [27]:
np.random.randint(1,6,1)    #np.random.randint(start , end , shape of array) 

array([3])

In [30]:
np.random.randint(1,600,[4,3,2])

array([[[389, 496],
        [165, 576],
        [350, 197]],

       [[153, 533],
        [438, 504],
        [350, 508]],

       [[199, 384],
        [298, 122],
        [251, 237]],

       [[537, 561],
        [197, 291],
        [169,  10]]])

In [31]:
np.random.seed(54)
np.random.randint(31,6000,[4,3])

array([[ 929, 3886, 5174],
       [3840, 3423, 2096],
       [5160, 5669, 4744],
       [3350, 4835, 3347]])

In [34]:
np.random.rand(4,3)    # array with float < 1and >0

array([[0.19555639, 0.71252488, 0.81638996],
       [0.47105727, 0.26108617, 0.44061904],
       [0.20938295, 0.47290381, 0.23138279],
       [0.16117695, 0.21706215, 0.16071548]])

In [38]:
np.loadtxt('somedata.txt',dtype = str)   #  to read ddata of any other file outside python extention

array(['file', 'outside', 'python', 'in', 'txt', 'formate'], dtype='<U7')

In [44]:
np.loadtxt('numdata.txt')    # txxt in form as writen in the file 

array([[ 23.,   3.,   3.,   5.],
       [ 63., 743.,   8.,  65.],
       [ 32., 424.,   4.,  24.]])

In [47]:
p = np.random.randint(2,100,[3,4])
p


array([[74, 60, 95, 40],
       [20, 24, 34, 95],
       [30, 39, 68, 30]])

In [57]:
np.savetxt('new.txt',p,delimiter=',')